# Generated by Django 5.1.3 on 2024-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositif',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='dispositif',
            index=models.Index(fields=['section', 'nom_lieu'], name='conso_dispo_section_4e19c1_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['entreprise', 'nom_section'], name='conso_secti_entrepr_2cf4f1_idx'),
        ),
    ]
